import { Component, computed, inject, input, output, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Producto } from '../../../productos/interfaces/producto';
import { ClientePedido, DatosPedido, LineaPedido } from '../../interfaces/pedido';
import { SelectorProductosPedidoComponent } from '../selector-productos-pedido/selector-productos-pedido.component';
import { PedidoService } from '../../services/pedido.service';

export interface LineaVista extends LineaPedido { nombre:string; precioUnitario:number; subtotal:number; }
@Component({selector:'app-pedido-formulario',imports:[ReactiveFormsModule,SelectorProductosPedidoComponent],templateUrl:'./pedido-formulario.component.html',styleUrls:['./pedido-formulario.component.css','./cliente-rapido.component.css']})
export class PedidoFormularioComponent {
  private readonly pedidoService=inject(PedidoService);
  readonly clientes=input.required<ClientePedido[]>();readonly productos=input.required<Producto[]>();readonly procesando=input(false);readonly esEdicion=input(false);readonly confirmar=output<DatosPedido>();
  readonly lineas=signal<LineaVista[]>([]);readonly idsAgregados=computed(()=>this.lineas().map(l=>l.productoId));readonly mensajeLinea=signal('');readonly total=computed(()=>this.lineas().reduce((s,l)=>s+l.subtotal,0));readonly hoy=new Date().toISOString().slice(0,10);
  readonly formulario=new FormGroup({clienteId:new FormControl('',{nonNullable:true,validators:[Validators.required]}),fechaEntrega:new FormControl<string|null>(null),observaciones:new FormControl('',{nonNullable:true,validators:[Validators.maxLength(1000)]})});
  readonly mostrandoCliente=signal(false);readonly guardandoCliente=signal(false);readonly errorCliente=signal('');readonly clientesLocales=signal<ClientePedido[]>([]);readonly todosLosClientes=computed(()=>[...this.clientes(),...this.clientesLocales()]);
  readonly formularioCliente=new FormGroup({nombre:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(100)]}),apellido:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(100)]}),rut:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^\d{1,2}\.?\d{3}\.?\d{3}-[\dkK]$/)]}),correo:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email,Validators.maxLength(150)]}),telefono:new FormControl('',{nonNullable:true,validators:[Validators.pattern(/^$|^[+\d][\d\s()-]{7,19}$/)]})});
  cargarInicial(datos:DatosPedido,productosHistoricos:Producto[]=[]):void{this.formulario.patchValue({clienteId:datos.clienteId,fechaEntrega:datos.fechaEntrega,observaciones:datos.observaciones??''});const disponibles=[...this.productos(),...productosHistoricos.filter(p=>!this.productos().some(x=>x.id===p.id))];this.lineas.set(datos.detalles.map(d=>{const p=disponibles.find(x=>x.id===d.productoId);return{...d,nombre:p?.nombre??'Producto',precioUnitario:p?.precioBase??0,subtotal:d.cantidad*(p?.precioBase??0)}}));if(this.esEdicion())this.formulario.controls.clienteId.disable();}
  agregarLinea(linea:LineaPedido):void{const p=this.productos().find(x=>x.id===linea.productoId);if(!p)return;this.mensajeLinea.set('');this.lineas.update(ls=>[...ls,{...linea,nombre:p.nombre,precioUnitario:p.precioBase,subtotal:linea.cantidad*p.precioBase}]);}
  cambiarCantidad(i:number,e:Event):void{const cantidad=Number((e.target as HTMLInputElement).value);if(!Number.isInteger(cantidad)||cantidad<=0)return;this.lineas.update(ls=>ls.map((l,n)=>n===i?{...l,cantidad,subtotal:cantidad*l.precioUnitario}:l));}
  quitar(i:number):void{this.lineas.update(ls=>ls.filter((_,n)=>n!==i));}
  enviar():void{this.mensajeLinea.set('');if(this.formulario.invalid||!this.lineas().length){this.formulario.markAllAsTouched();if(!this.lineas().length)this.mensajeLinea.set('Agrega al menos un producto al pedido.');return;}const v=this.formulario.getRawValue();this.confirmar.emit({clienteId:v.clienteId,fechaEntrega:v.fechaEntrega||null,observaciones:v.observaciones.trim()||null,detalles:this.lineas().map(({productoId,cantidad,personalizacion})=>({productoId,cantidad,personalizacion}))});}
  async registrarCliente():Promise<void>{if(this.formularioCliente.invalid||this.guardandoCliente()){this.formularioCliente.markAllAsTouched();return;}this.guardandoCliente.set(true);this.errorCliente.set('');try{const v=this.formularioCliente.getRawValue();const cliente=await this.pedidoService.registrarCliente({nombre:v.nombre.trim(),apellido:v.apellido.trim(),rut:v.rut.trim(),correo:v.correo.trim().toLowerCase(),telefono:v.telefono.trim()||null});this.clientesLocales.update(c=>[...c,cliente]);this.formulario.controls.clienteId.setValue(cliente.id);this.mostrandoCliente.set(false);this.formularioCliente.reset();}catch{this.errorCliente.set('No fue posible registrar el cliente. Verifica que el correo y RUT no estén registrados.');}finally{this.guardandoCliente.set(false);}}
}
